uju-in/lime-backend

- lime-api/src/main/java/com/programmers/lime/domains/bucket/api/BucketController.java
- lime-api/src/main/java/com/programmers/lime/domains/bucket/api/dto/request/BucketCreateRequest.java
- lime-api/src/main/java/com/programmers/lime/domains/bucket/api/dto/request/BucketUpdateRequest.java
- lime-api/src/main/java/com/programmers/lime/domains/bucket/api/dto/response/BucketGetResponse.java
- lime-api/src/main/java/com/programmers/lime/domains/feed/api/FeedController.java
- lime-api/src/main/java/com/programmers/lime/domains/hobby/HobbyController.java
- lime-api/src/main/java/com/programmers/lime/domains/hobby/api/dto/response/HobbyGetResponse.java
- lime-api/src/main/java/com/programmers/lime/domains/hobby/api/dto/response/HobbyItem.java
- lime-api/src/main/java/com/programmers/lime/domains/hobby/application/HobbyService.java
- lime-api/src/main/java/com/programmers/lime/domains/inventory/api/InventoryController.java
- lime-api/src/main/java/com/programmers/lime/domains/inventory/api/dto/response/InventoryGetResponse.java
- lime-api/src/main/java/com/programmers/lime/domains/item/api/ItemController.java
- lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/ItemEnrollRequest.java
- lime-api/src/main/java/com/programmers/lime/domains/vote/api/VoteController.java
- lime-api/src/main/java/com/programmers/lime/domains/vote/api/dto/request/VoteCreateRequest.java
- lime-domain/src/main/java/com/programmers/lime/common/model/Hobby.java
- lime-domain/src/main/java/com/programmers/lime/domains/bucket/model/BucketProfile.java
- lime-domain/src/main/java/com/programmers/lime/domains/feed/model/FeedInfo.java
- lime-domain/src/main/java/com/programmers/lime/domains/inventory/model/InventoryInfoSummary.java
- lime-domain/src/main/java/com/programmers/lime/domains/inventory/model/InventoryProfile.java
<br>
NO-JIRA
- 취미를 한글로 통일한다.
- 새롭게 정한 취미 키워드에 맞게 취미를 추가하고 삭제한다.
- 스포츠
- 농구, 배드민턴, 클라이밍, 헬스, 야구
- 라이프 스타일
- 요리, 게임, 데스크테리어, 그림, 음악
<br>
- 취미를 영어로 사용하고 있던 곳을 모두 한글로 변경하였습니다.
- 취미를 한글로 통일하면서 취미를 조회하는 메서드의 이름이 변경되었습니다. (한글만 있으므로 from으로 통일)
> [NO-JIRA] 취미 요구사항 변경

- lime-api/src/main/java/com/programmers/lime/global/config/security/auth/handler/OAuth2LoginSuccessHandler.java
- lime-api/src/main/java/com/programmers/lime/global/config/security/jwt/JwtService.java
<br>
LIME-1
1. 헤더에 accessToken이 프로필 등록 이후 두번 보내지는 문제 수정,
2. redirect를 할 경우 헤더에 있는 정보는 새로운 요청을 생성할 때 저장할 수 없고 삭제된다.이 방법을 쿠키로 해결함
쿠키로 전달하게 되면서 쿠키의 사용 시간동안 요청이 끝나고 새로운 요청이 만들어져도 살아있을 수 있어 프론트는 해당 정보를 저장할 수 있을 것으로 기대됨
<br>
> [LIME-1] 일부 버그 수정. redirect 에 토큰 정보 쿠키로 전달

- lime-api/src/main/java/com/programmers/lime/domains/member/api/MemberController.java
- lime-api/src/main/java/com/programmers/lime/domains/member/application/MemberService.java
- lime-domain/src/main/java/com/programmers/lime/domains/member/implementation/MemberChecker.java
- lime-domain/src/test/java/com/programmers/lime/domains/member/implementation/MemberCheckerTest.java
- lime-domain/src/test/java/com/programmers/lime/domains/member/implementation/MemberRemoverTest.java
<br>
NO-JIRA
```
- 닉네임 중복 시 예외가 발생하는 대신 bool 타입으로 반환하도록 변경
- 중복이면 true, 중복이 아니면 false
```
<br>
- 위의 설명과 동일함
> [NO-JIRA] 닉네임 중복 시 예외 대신 bool 타입으로 반환하도록 변경

- lime-api/src/main/java/com/programmers/lime/domains/item/api/ItemController.java
- lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemService.java
- lime-api/src/main/java/com/programmers/lime/global/cursor/CursorRequest.java
- lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/ItemCursorReader.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/model/ItemSortCondition.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemRepositoryForCursor.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemRepositoryForCursorImpl.java
<br>
LIME -50 
REVIEW_COUNT_DESC(아이템 리뷰 많은 순 정렬),
REVIEW_RATING_DESC(아이템 리뷰 평점 높은 순 정렬),
NEWEST(최신 순 정렬),
PRICE_HIGH_TO_LOW(아이템 가격 높은 순 정렬),
PRICE_LOW_TO_HIGH(아이템 가격 낮은 순 정렬);
- 정렬할 때 review 테이블의 정보가 필요하여 item id를 기준으로 item과 review를 join 하였습니다. 
- item에 대해 review가 있는 경우 join을 하고 없는 경우에도 item을 조회할 수 있도록 leftjoin을 추가하였습니다
- item id 기준으로 group by 하여 집계 함수를 사용하였고 이를 기준으로 정렬 하도록 하였습니다. 
- 정렬 조건이 없는 경우 아이템이 추가 된 순서대로 반환 됩니다.
> [LIME-50] 아이템 목록 조회 정렬 조건 추가

- lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/response/ItemGetResponse.java
- lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemService.java
- lime-api/src/main/java/com/programmers/lime/domains/item/application/dto/ItemGetServiceResponse.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFavoriteInfoReader.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemReader.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/model/MemberItemMetadata.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemRepository.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewStatistics.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewRepository.java
<br>
- 아이템 상세조회 할 경우 찜 개수도 함께 반환 되도록 추가하였습니다. 7c5dba254be275ab953c5de100624a49ece986d3 😊❤
- 리뷰가 없는 아이템을 상세 조회할 경우 평점이 null에서 0으로 반환 되도록 수정 9e6249058efc7d309fd81fba7f25f300cb295ab9 😊❤
[LIME-54]
- 아이템 상세조회 
```json
{
"itemInfo": {
"id": 6,
"name": "Bsun Moon 비선문 투명 리니어 스위치",
"price": 250,
"image": "https://shop-phinf.pstatic.net/20231115_7/1700016570031xpelT_JPEG/6564982989305255_1916464417.JPG?type=m510"
},
"itemUrl": "https://smartstore.naver.com/pompokey/products/8814129912?NaPm=ct%3Dlpktmvgg%7Cci%3D643183b5ccd7907ac35e9e2aa270bfc2363ffe6b%7Ctr%3Dslsl%7Csn%3D4954554%7Chk%3D60c8b01e78a6d310ccb29fecaa9a175f5e366d02",
"itemAvgRate": 0.0,
"isMemberItem": true,
"isReviewed": false,
"favoriteCount": 1
}
```
[LIME-54]: …
> [LIME-54] 아이템 상세조회 기능추가 

- lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemService.java
- lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/ItemCursorReader.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/model/FavoriteInfoForItemSummary.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/model/ItemCursorIdInfo.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/model/ItemInfoForItemSummary.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/model/ItemSummary.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/model/ReviewInfoForItemSummary.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemRepositoryForCursor.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemRepositoryForCursorImpl.java
- lime-domain/src/test/java/com/programmers/lime/domains/item/implementation/ItemCursorReaderTest.java
- lime-domain/src/testFixtures/java/com/programmers/lime/common/cursor/CursorIdBuilder.java
- lime-domain/src/testFixtures/java/com/programmers/lime/domains/item/model/FavoriteInfoForItemSummaryBuilder.java
- lime-domain/src/testFixtures/java/com/programmers/lime/domains/item/model/ItemCursorIdInfoBuilder.java
- lime-domain/src/testFixtures/java/com/programmers/lime/domains/item/model/ItemCursorSummaryBuilder.java
- lime-domain/src/testFixtures/java/com/programmers/lime/domains/item/model/ItemInfoForItemSummaryBuilder.java
- lime-domain/src/testFixtures/java/com/programmers/lime/domains/item/model/ItemSummaryBuilder.java
- lime-domain/src/testFixtures/java/com/programmers/lime/domains/item/model/ReviewInfoForItemSummaryBuilder.java
<br>
아이템 목록 조회에 찜 개수, 리뷰 수 추가하였습니다. 😊❤ dc0163a4e7e82a6419e251308389c6a66b29d680
[LIME-57]
- 기존 아이템 목록조회에 찜 개수, 리뷰 수를 추가하기위해 MemberItem, Review 엔티티에 있는 정보를 가져와야 합니다.
- 아이템 목록조회 하기 위해서 Item, MemberItem, Review 엔티티를 조인해야 합니다.
- 기존 방법으로 repository에서 이를 모두 해결 하였지만 그로 인해 N+1 문제 발생, repository에 의존적인 코드 작성 등의 문제가 있었습니다.
- N+1 문제도 해결 책은 있었지만 3개 이상의 테이블을 조인하게 되면 결국 N+1 문제가 발생하거나 코드가 너무 복잡해졌습니다.
- 이 문제를 해결하기 위해 where in을 활용한 서브쿼리를 이용하였습니다.
- repository에 아이템 데이터를 가져올 때 아이템 아이디와 커서 아이디를 포함하는 ItemCursorInfo 리스트를 가져 옵니다. (ItemCursorReader 클래스에 56번~62번 라인 참조 dc0163a4e7e82a6419e251308389c6a66b29d680) 
- repository에서는 입력받은 아이템 아이디를 이용하여 Item 엔티티와 각각의 엔티티와 join하여 데이터를 반환합니다. 
- ItemCursorInfo 리스트를 이용하여 ItemSummary 클래스를 만드는데 필요한 도메인과 각각 조인 합니다. (ItemCursorReader 클래스의 …
> [LIME-57] 아이템 목록 조회에 찜 개수, 리뷰 수 추가

- lime-api/src/main/java/com/programmers/lime/domains/review/api/ReviewController.java
- lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewService.java
- lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/domain/ReviewImage.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewAppender.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewCursorReader.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewImageAppender.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/model/MemberInfoWithReviewId.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/model/ReviewCursorIdInfo.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/model/ReviewCursorSummary.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/model/ReviewSummary.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewImageRepository.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewRepositoryForCursor.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewRepositoryForCursorImpl.java
- lime-domain/src/test/java/com/programmers/lime/domains/review/implementation/ReviewCursorReaderTest.java
- lime-domain/src/testFixtures/java/com/programmers/lime/domains/member/domain/MemberInfoBuilder.java
- lime-domain/src/testFixtures/java/com/programmers/lime/domains/member/domain/MemberInfoWithReviewIdBuilder.java
- lime-domain/src/testFixtures/java/com/programmers/lime/domains/review/ReviewCursorIdInfoBuilder.java
- lime-domain/src/testFixtures/java/com/programmers/lime/domains/review/ReviewCursorSummaryBuilder.java
- lime-domain/src/testFixtures/java/com/programmers/lime/domains/review/ReviewSummaryBuilder.java
- lime-infrastructure/src/main/java/com/programmers/lime/s3/S3Manager.java
<br>
리뷰 이미지 관련 기능 추가 ❤❤
- 리뷰 등록할 때 이미지 여러개 넣을 수 있도록 기능 추가 92665c7d7ef09c7cb472d3d4f3c55207da2247ad
- 리뷰 조회할 때 이미지 조회할 수 있도록 기능 추가 8650439f504817455088b326dcde965b4b71f45d
[LIME-58]
- 프론트에서 form-data로 Multipartfile을 전송 받으면 서버에서 네이버 클라우드 버킷으로 전송합니다.
- 이 후 네이버 클라우드에 저장되어있는 이미지의 주소를 리뷰 이미지 테이블에 리뷰 아이디를 pk로 하여 저장합니다. 632131ed8b8c5f4c21f5b5b12a783e6487a588c8 92665c7d7ef09c7cb472d3d4f3c55207da2247ad
- https://github.com/uju-in/lime-backend/pull/24 책임 분산 부분에서 설명한 것과 같이 리뷰 목록 조회도 where in 서브쿼리를 활용하여 이미지 주소 조회 기능을 추가하였습니다.
[LIME-58]: https://uju-lime.atlassian.net/browse/LIME-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIME-58] 리뷰 이미지 추가 

- lime-api/src/main/java/com/programmers/lime/domains/review/api/ReviewController.java
- lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewService.java
- lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewCursorReader.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/model/ReviewSortCondition.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewRepositoryForCursor.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewRepositoryForCursorImpl.java
- lime-domain/src/test/java/com/programmers/lime/domains/review/implementation/ReviewCursorReaderTest.java
<br>
- NEWEST(최신순), LOWEST_RATE(평점 낮은 순), HIGHEST_RATE(평점 높은 순)등의 정렬 조건을 추가하였습니다. ded2b633195dd19dd1a92ef230826e2132ef98af
- LIKE_COUNT_DESC(좋아요 순)은 좋아요 기능이 추가 되면 추가 됩니다. 
- 정렬조건 추가로 인한 테스트 코드 수정 2c88b0126512db0df216d88c4284a983762edff4
[LIME-66]
- 정렬 조건을 추가하기 위해 generateCursorId 메서드를 수정 하였습니다.
- 기존에 정렬을 위해 date기준으로 커서 아이디를 만들었습니다. 
- 이를 응용하여 generateCursorId에 각 정렬기준 마다 데이터를 변경하여 커서 아이디를 생성하게 하였습니다.
[LIME-66]: https://uju-lime.atlassian.net/browse/LIME-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIME-66]  리뷰 목록 조회 정렬 조건 추가 

- lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewService.java
- lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewValidator.java
- lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewAppender.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewReader.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewRepository.java
<br>
[LIME-51]
- 이미지를 업로드 하지 않으면 내용이 없는 multipart file이 tomcat에서 올라오고 있었습니다.
- 파일 이름이 없는 multipart file은 무시하도록 filter를 추가하여 해결하였습니다.
- 사용자가 어떤 아이템에 대해 리뷰를 하였다면 중복으로 추가되지 않도록 기능추가 하였습니다. 
<br>
[LIME-51]: https://uju-lime.atlassian.net/browse/LIME-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIME-51] 리뷰 관련 버그 수정 및 제약사항 추가

- lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewService.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewImageRemover.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewLikeRemover.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewImageRepository.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewLikeRepository.java
<br>
- fk 제약 설정으로 인해 db에서 예외 발생하였습니다.
- review_likes, review_images에 review id가 있는 경우 관련 row를 삭제하고 review를 삭제 하도록 변경하였습니다. 
[LIME-93]
[LIME-93]: https://uju-lime.atlassian.net/browse/LIME-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIME-93]리뷰 이미지와 리뷰 좋아요가 있는 경우 삭제 안되는 버그 수정

- lime-api/src/main/java/com/programmers/lime/domains/item/api/ItemController.java
- lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/MemberItemMoveRequest.java
- lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemService.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/domain/MemberItem.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemAppender.java
<br>
[LIME-95] 
- 찜 아이템 아이디가 나의 아이템인지 검증 합니다.
- 이동할 폴더 아이디도 나의 폴더인지 확인 합니다.
- 이 후 찜 아이템의 folder_id를 변경하고 데이터 베이스에 저장 합니다. 
- folder_id가 null 이면 최상위 폴더에 있다는 의미 입니다. 😊
[LIME-95]: https://uju-lime.atlassian.net/browse/LIME-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIME-95] 찜 폴더 이동 기능 추가

- lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderFavoriteInfoReader.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/model/MemberItemFolderMetadata.java
<br>
- 폴더 안에 포함되어 있는 아이템 수를 반환 하도록 기능이 추가되었습니다.
[LIME-96]
[LIME-96]: https://uju-lime.atlassian.net/browse/LIME-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIME-96] 폴더에 포함되어 있는 아이템 개수 반환 기능 추가

- lime-api/src/main/java/com/programmers/lime/domains/vote/api/VoteController.java
- lime-api/src/main/java/com/programmers/lime/domains/vote/application/VoteService.java
- lime-domain/src/main/java/com/programmers/lime/domains/vote/model/VoteSortCondition.java
- lime-domain/src/main/java/com/programmers/lime/domains/vote/model/VoteStatusCondition.java
- lime-domain/src/main/java/com/programmers/lime/domains/vote/repository/VoteRepositoryForCursorImpl.java
- lime-domain/src/test/java/com/programmers/lime/domains/vote/implementation/VoteReaderTest.java
- lime-domain/src/testFixtures/java/com/programmers/lime/domains/vote/model/VoteCreateImplRequestBuilder.java
<br>
LIME-91
- 기존의 상태 조건은 `종료된 투표`, `진행 중인 투표`, `내가 올린 투표`, `내가 참여한 투표` 4가지가 있었습니다.
- 변경된 요구사항은 종료된 투표와 진행 중인 투표를 함께 보여줘야 하기 때문에 투표 상태 조건에서 `종료된 투표`, `진행 중인 투표`를 삭제하였습니다.
- 따라서 상태 조건이 필수 값에서 옵션 값으로 변경되었고, 클라이언트 측에서 상태 조건을 보내지 않을 경우 조건절에 걸리지 않도록 null로 처리하였습니다.
- 기존의 정렬 조건은 `인기순`, `최신순` 2가지가 있었고, 여기에 `마감순`을 추가하였습니다.
- 마감순은 투표 마감 시간으로 정렬하였습니다.
<br>
- 위에서 설명한 바와 같습니다.
> [LIME-91] 투표 목록 조회 요구사항 변경 - 투표 상태 조건, 정렬 조건 수정

- lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewService.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewLikeRemover.java
<br>
- 리뷰 취소를 할 경우 review_images 테이블에서 관련 row를 삭제합니다.
- 이 때 다음과 같은 예외가 발생하였습니다. `No EntityManager with actual transaction available for current thread - cannot reliably process 'remove' call`
- 메시지를 해석하면 스레드에 transaction이 없어 remove 호출을 신뢰할 수 없다는 의미입닌다.
- @Transcational 을 리뷰 좋아요 삭제 메서드에 붙여주어 원인을 해결하였습니다.
- 리뷰를 수정할 때 기존 이미지 url을 프론트에서 넘겨주면 삭제하는 로직이 있습니다.
- 백엔드용 UI에서는 이미지가 입력으로 들어오지 않으면 emty list를 반환 해서 잘 작동하였습니다.
- 프론트에서 구현한 UI에서는 이미지 URL을 주지 않으면 null인 리스트를 반환해서 NPE 발생하였습니다.
- 따라서 list가 null일 경우 메서드를 early stop 하는 방식으로 버그를 수정하였습니다. 
[LIME-111]
[LIME-111]: https://uju-lime.atlassian.net/browse/LIME-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIME-111] 리뷰 관련 버그 수정 

- lime-api/src/main/java/com/programmers/lime/domains/vote/application/VoteService.java
- lime-infrastructure/src/main/java/com/programmers/lime/redis/vote/VoteRankingInfo.java
<br>
NO-JIRA
- 투표 랭킹을 조회할 때, 동점 순위에 대해서는 투표 마감 임박순(=투표 마감 시각이 더 빠른 순)으로 정렬
- 투표 id가 더 낮을수록 투표 마감 시각이 더 빠르기 때문에, 낮은 투표 Id가 더 높은 값을 가지도록 하기 위해서 Long의 최댓값에서 뺀 값을 저장하도록 하였습니다.
- 투표 마감 임박에 대해서, 최대 투표 인원 수가 다 차기 직전인 투표까지 고려하기엔 너무 복잡한 관계로 투표 마감 시각에 대해서만 고려하였습니다.
https://github.com/Yiseull/dev-qna/issues/9
<br>
> [NO-JIRA] 투표 랭킹 순위가 같을 경우, 투표 마감 시각이 빠른 순으로 정렬되도록 수정

- lime-domain/src/main/java/com/programmers/lime/domains/bucket/domain/Bucket.java
- lime-domain/src/main/java/com/programmers/lime/domains/bucket/domain/BucketItem.java
- lime-domain/src/main/java/com/programmers/lime/domains/bucket/implementation/BucketAppender.java
- lime-domain/src/main/java/com/programmers/lime/domains/bucket/implementation/BucketRemover.java
- lime-domain/src/main/java/com/programmers/lime/domains/bucket/repository/BucketItemRepository.java
- lime-domain/src/test/java/com/programmers/lime/domains/bucket/implementation/BucketAppenderTest.java
<br>
LIME - 103
JPA의 saveAll 메소드를 사용하면 문제가 있다.
List 자료형으로 데이터를 업로드하게되면 저장되는 엔티티마다 save메소드가 일일히 발생한다. 
그러기 때문에 쿼리도 insert 쿼리가 여러번 만들어져 나가게 된다.
이런 문제를 해결해기 위해 JdbcTemplate를 사용했다.
네이티브 쿼리를 사용하고 batch 단위로 데이터를 insert할 수 있기 때문에 쿼리가 한번만 나가게 된다.
JPA 대산 jdbc를 사용하는 이유
1. 복잡한 쿼리를 대신한다.
2. 쿼리의 성능을 개선한다.
3. 반환값을 원하는대로 커스텀 한다.
<br>
> [LIME-103] Bucket bulk-insert 리팩토링

- lime-api/src/main/java/com/programmers/lime/domains/item/api/ItemController.java
- lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/ItemSearchRequest.java
- lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/response/ItemGetByCursorResponse.java
- lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemService.java
- lime-api/src/main/java/com/programmers/lime/domains/item/application/dto/ItemGetByCursorServiceResponse.java
- lime-domain/src/main/java/com/programmers/lime/domains/bucket/implementation/BucketAppender.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/ItemCursorReader.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/ItemReader.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemCustomRepository.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemCustomRepositoryImpl.java
- lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemRepositoryForCursorImpl.java
<br>
- keyword, hobby에 따라 전체 아이템수를 다르게 반환해야 해서 이부분은 query dsl로 만들었습니다.
- 전체 아이템 수를 Long으로 변경한 이유
- query dsl에서는 fetch count를 사용해야하는데 기본적으로 Long을 반환 합니다.
- Long을 integer로 repository에서 변경 가능하지만 이렇게 되면 예외처리와 변환 할 때 추가적인 비용이 필요합니다.
- 백엔드에서 이 값으로 int와 연산을 하지 않고 프론트에서는 number로 받고 있어서 int, Long 반환 값의 차이는 없다고 생각합니다.
- 그래서 총 아이템수를 반환하는 dto의 타입을 Long으로 수정하였습니다. 
[NO-JIRA]
> [NO-JIRA] 아이템 검색 기능 변경

- lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderReader.java
<br>
- transactional이 readonly로 인해 폴더가 생성되지 생성되지 않는 버그가 있습니다.
- MemberItemFolderReader클래스의 getDefaultFolderId메서드와 MemberItemFolderAppender클래스의 append 메서드 두개 중에 transactional을 getDefaultFolderId 메서드에 붙였습니다.
- 이렇게 한 이유는 append메서드만 보면 transactional을 붙여야할 이유가 없습니다.
- 따라서 추후 유지보수 과정에서 transcational을 제거할 수 있고 이때 버그가 발생할 수 있다고 생각됩니다.
- 추가로 "@Transactional(readOnly = true) "으로 DB의 변경 가능성이 없다고 표시한 MemberItemFolderReader 클래스에 예외적으로 getDefaultFolderId메서드에는 변경될 수 있음을 표기하는게 맞다고 생각합니다.
[LIME-107]
[LIME-107]: https://uju-lime.atlassian.net/browse/LIME-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIME-107] transactional이 readonly로 인해 폴더가 생성되지 않는 버그 수정

- lime-api/src/main/java/com/programmers/lime/domains/vote/api/VoteController.java
- lime-api/src/main/java/com/programmers/lime/global/cursor/CursorRequest.java
- lime-domain/src/main/java/com/programmers/lime/domains/vote/repository/VoteRepositoryForCursorImpl.java
<br>
NO-JIRA
- Cursor Id와 사이즈는 필수가 아닌 옵션 쿼리 파라미터로 @ModelAttribute를 이용하여 DTO로 받고 있습니다. 
- 하지만 Swagger 상으로는 두 값이 json 형식으로 함께 받고 있으며, 필수 값으로 지정되어 있습니다.
- 찾아보니 SpringDoc 이슈이며, 저희가 의도한 대로 각각 쿼리 파라미터로 옵션으로 받기 위해서는 추가적인 작업이 필요하다고 나와있습니다.
- 일단 **각각의 값을 쿼리 파라미터로 사용**하기 위해, 컨트롤러의 매개변수 부분 또는 DTO 클래스단에 `@ParameterObject`를 추가하면 됩니다. 저희 서비스는 CursorRequest DTO가 공용으로 사용되기 때문에 DTO에 붙여줬습니다~!
- `@ParameterObject`를 적용하고 나니, **모든 필드를 String으로 인식하는 현상이 발생**하였습니다. 이 문제를 해결하기 위해 @Schema 대신 @Parameter로 대체하여 해결하였습니다!
왼쪽 화면(기존), 오른쪽 화면(변경)
https://yeonyeon.tistory.com/324
- `총 검색된 투표 수`와 `실제 검색되는 투표`가 일치하지 않는 문제가 있었습니다.
- 코드를 확인하니까 `총 검색된 투표 수`는 마감된 투표에 대해서만 count 하고, `실제 검색되는 투표`는 마감된 투표와 함께 진행 중인 투표도 보여주고 있었습니다.
- 팀 회의를 통해 마감 중인 투표와 진행 중인 투표를 모두 보여주기로 결정하여서, 그대로 코드를 수정했습니다!
- 기존에는 …
> [NO-JIRA] fix vote keyword

- lime-infrastructure/src/main/java/com/programmers/lime/redis/vote/VoteRedisManager.java
<br>
NO-JIRA
- 투표 랭킹에 올라간 투표들이 시간이 지나도 지워지지 않는 버그가 있었습니다.
- 이전에 투표 랭킹을 취미별로 조회하는 요구사항이 추가되면서 레디스 키 값을 'VOTE_{취미}'로 변경하였는데, ttl를 설정하는 코드에는 추가되지 않아서 생긴 문제였습니다.
- 레디스 ttl을 설정하는 명령어에 키 값을 수정하여 해결하였습니다.
<br>
> [NO-JIRA] 투표 랭킹에서 ttl 적용 안되는 문제 해결

- lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderFavoriteInfoReader.java
<br>
- 찜 목록 조회할 경우 default 폴더가 가장 뒤에 오도록 기능 추가 하였습니다. df88298e0bf55fee8952bb3bd4548fff4b88015f
[ LIME-133]
- moveDefaultFolderToEnd 메서드에서 default 폴더를 뒤로 이동시킵니다.
- memberItemFolders에서 폴더 이름이 default인 경우 removeIf로 삭제하고 defaultFolders에 임시로 저장합니다.
- stream이 종료되면 memberItemFolders의 마지막에 임시로 저장한 defaultFolders를 추가합니다. 
<br>
> [LIME-133] default 폴더를 가장 뒤에 오도록 기능 추가

- lime-api/src/main/java/com/programmers/lime/domains/review/api/dto/request/ReviewCreateRequest.java
- lime-api/src/main/java/com/programmers/lime/domains/review/api/dto/request/ReviewUpdateRequest.java
<br>
- 리뷰 내용 수정, 삭제할 경우 최소 10 글자 제약 사항 추가 06b0971f0f593039701e3ada0fd411b1645261db
- controller에서 잡도록 수정하였습니다.
[LIME-134]
[LIME-134]: https://uju-lime.atlassian.net/browse/LIME-134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIME-134] 리뷰 내용 최소 글자 추가

- lime-api/build.gradle
- lime-api/src/main/java/com/programmers/lime/domains/vote/api/VoteController.java
- lime-api/src/main/java/com/programmers/lime/global/cursor/CursorRequest.java
- lime-api/src/test/java/com/programmers/lime/domains/vote/application/VoteServiceTest.java
- lime-domain/src/main/java/com/programmers/lime/domains/vote/repository/VoteRepositoryForCursorImpl.java
- lime-domain/src/testFixtures/java/com/programmers/lime/domains/vote/domain/VoteBuilder.java
- lime-domain/src/testFixtures/java/com/programmers/lime/domains/vote/domain/setup/VoteSetUp.java
- lime-domain/src/testFixtures/java/com/programmers/lime/domains/vote/domain/setup/VoterSetUp.java
<br>
LIME-119
- 테스트명은 기능 명세서와 같이 작성하였습니다. 그 이유는 저희 서비스가 비지니스 명세 역할을 하고 있기도 하고, 테스트 코드가 기능 명세 역할 한다는 이야기를 들은 적이 있어서 이렇게 작성하였습니다.
- 각각 기능에 대해 가능한 모든 시나리오에 대해 테스트를 작성하였습니다. 그 이유는 추후 리팩토링이나 기능 변경이 있을 경우 테스트로 빠르게 확인하기 위함입니다.
- 투표 검색 테스트는 투표 검색 기능에 대해 의논이 끝난 후 추가 작성해서 올리겠습니다!
- 현재 로컬 DB를 이용해서 테스트를 진행해야 합니다. 그래서 테스트만을 위한 독립적인 DB를 구성하기 위해 H2를 사용하고자 했으나, H2에는 MySQL의 DATE_FORMAT 함수를 대체할 수 있는 함수가 없어서 목록 조회 테스트에서 실패합니다.
- 이를 해결하고자, DATE_FORMAT을 사용자 정의 함수로 만들어서 H2에 올리는 방법을 시도해보았으나 실패하여서 일단 H2 의존성을 다시 제거하였습니다😭
- 여유가 있을 때 위의 방법을 다시 시도해볼 생각입니다! 다같이 더 나은 방법이 없는지 찾아봐도 좋을 것 같습니다😊
- 아래 문서에 정리해놓았으니 참고해주세용!!
[@SpringBootTest 에서 LazyInitializationException 트러블슈팅](https://github.com/Yiseull/dev-qna/blob/main/%ED%8A%B8%EB%9F%AC%EB%B8%94%EC%8A%88%ED%8C%85/%40SpringBootTest%20%EC%97%90% …
> [LIME-119] 투표 통합 테스트 추가

- lime-api/src/main/java/com/programmers/lime/LimeApplication.java
- lime-api/src/main/java/com/programmers/lime/domains/vote/application/VoteService.java
- lime-api/src/main/java/com/programmers/lime/global/event/ranking/vote/RankingAddEvent.java
- lime-api/src/main/java/com/programmers/lime/global/event/ranking/vote/RankingDecreasePopularityEvent.java
- lime-api/src/main/java/com/programmers/lime/global/event/ranking/vote/RankingDeleteEvent.java
- lime-api/src/main/java/com/programmers/lime/global/event/ranking/vote/RankingEventListener.java
- lime-api/src/main/java/com/programmers/lime/global/event/ranking/vote/RankingUpdateEvent.java
- lime-api/src/test/java/com/programmers/lime/domains/vote/application/VoteServiceTest.java
- lime-domain/src/testFixtures/java/com/programmers/lime/domains/member/domain/MemberBuilder.java
- lime-infrastructure/src/main/java/com/programmers/lime/redis/vote/VoteRedisManager.java
<br>
LIME-131
- 투표 로직이 정상적으로 처리 되어도 레디스에 문제가 생기면(예외가 터지면) 응답으로 예외 메시지를 보여준다.
- QA를 진행할 때, 투표를 생성하였는데 레디스 서버에 문제가 생겨서 응답으로 예외 메시지를 받았다. 하지만 투표는 정상적으로 생성되었다. (DB에 Insert 됨)
- **투표 로직과 레디스 로직을 분리**하여, 레디스에 문제가 생겨도 응답은 정상적으로 내려주도록 변경한다.
> 이벤트 처리 + 비동기
- 레디스 로직들을 이벤트로 처리하여 투표 로직과 분리하였습니다.
- 하지만 이벤트는 기본적으로 동기로 작동하기 때문에, 예외가 전파됩니다. 이를 해결하기 위해 이벤트를 처리하는 메서드에 `@Async` 어노테이션을 붙여주어 비동기로 처리하였습니다.
- 비동기로 처리할 경우, 예외가 발생해도 호출 스레드로 예외가 전파되지 않습니다. 따라서 레디스 로직은 투표 로직에 영향을 미치지 않습니다.
> `@TransactionalEventListener`을 사용하지 않은 이유
- `@TransactionalEventListener`는 default가 AFTER_COMMIT 입니다. 따라서 이 어노테이션을 사용하면 커밋된 후에 이벤트가 실행됩니다. 
- 하지만 VoteService 메서드들에는 `@Transactional`이 붙어있지 않아서 `@TransactionalEventListener`가 작동하지 않습니다.
- 또한 구현 계층 메서드에 `@Transactional`가 붙어있어 투표 로직들이 DB에 반영된 후(commit된 …
> [LIME-131] 이벤트 비동기 처리를 통해 투표 로직과 레디스 로직 분리

- lime-api/src/main/java/com/programmers/lime/domains/feed/application/FeedService.java
- lime-api/src/main/java/com/programmers/lime/global/event/ranking/feed/FeedRankingUpdateEvent.java
- lime-api/src/main/java/com/programmers/lime/global/event/ranking/feed/FeedRankingUpdateEventListener.java
<br>
###피드 랭킹 업데이트를 이벤트로 처리 하도록 기능 추가
[LIME-136]
- 피드 생성, 좋아요, 싫어요를 할 경우 동기적으로 랭킹을 업데이트 해야 합니다.
- 하지만 사용자 관점에서 랭킹 업데이트가 될 때 까지 stop될 이유가 없었습니다.
- 이 문제점을 해결하기 위해 랭킹 업데이트 기능을 @Async를 사용하여 비동기적으로 실행되게 만들었습니다. 0e63c9dc42ea683060815ad4d1a0f79deceaee5a
[LIME-136]: https://uju-lime.atlassian.net/browse/LIME-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIME-136] 피드 랭킹 업데이트 이벤트로 비동기 처리 기능 추가 

- lime-api/src/main/java/com/programmers/lime/domains/chatroom/api/ChatRoomController.java
- lime-api/src/main/java/com/programmers/lime/domains/chatroom/api/dto/response/ChatRoomGetListResponse.java
- lime-api/src/main/java/com/programmers/lime/domains/chatroom/application/ChatRoomService.java
- lime-api/src/main/java/com/programmers/lime/domains/chatroom/application/dto/response/ChatRoomGetServiceListResponse.java
- lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
- lime-domain/src/main/java/com/programmers/lime/domains/chatroom/domain/ChatRoom.java
- lime-domain/src/main/java/com/programmers/lime/domains/chatroom/domain/ChatRoomMember.java
- lime-domain/src/main/java/com/programmers/lime/domains/chatroom/implementation/ChatRoomMemberAppender.java
- lime-domain/src/main/java/com/programmers/lime/domains/chatroom/implementation/ChatRoomMemberReader.java
- lime-domain/src/main/java/com/programmers/lime/domains/chatroom/implementation/ChatRoomMemberRemover.java
- lime-domain/src/main/java/com/programmers/lime/domains/chatroom/implementation/ChatRoomReader.java
- lime-domain/src/main/java/com/programmers/lime/domains/chatroom/model/ChatRoomInfo.java
- lime-domain/src/main/java/com/programmers/lime/domains/chatroom/model/ChatRoomStatus.java
- lime-domain/src/main/java/com/programmers/lime/domains/chatroom/model/ChatRoomType.java
- lime-domain/src/main/java/com/programmers/lime/domains/chatroom/repository/ChatRoomMemberRepository.java
- lime-domain/src/main/java/com/programmers/lime/domains/chatroom/repository/ChatRoomQueryDsl.java
- lime-domain/src/main/java/com/programmers/lime/domains/chatroom/repository/ChatRoomQueryDslImpl.java
- lime-domain/src/main/java/com/programmers/lime/domains/chatroom/repository/ChatRoomRepository.java
<br>
- 채팅방 목록 조회(전체
- 채팅방 참여
- 채팅방 인원수 조회
- 채팅방 나가기 기능 
[LIME-141]
- 데이터 베이스에 있는 참여 가능한 전체 채팅방을 조회 합니다.
- memberId가 있는 경우와 없는 경우를 나눠서 조회 합니다.
- memberId가 있는 경우 chat_rooms과 chat_room_members 테이블과 left join 하여 입력으로 받은 memberId가 일치하는지 확인합니다. 이 때 일치하는 memberId가 chat_room_members에 있다면 isJoined를 true 반환하고 아니면 false로 반환 합니다.
- memberId가 없는 경우 위 작업을 생략하고 isJoined를 false로 반환 합니다.
- 채팅방 목록 조회 요구사항이 복잡해서  Querydsl로 구현 하였습니다.
-  room id는 path variable로 받고 token은 헤더에서 가져와 처리합니다.
- jpa repository의 save 메서드를 사용하여 저장합니다ㅏ.
-  room id를 입력받아 chat_rooom_members 테이블을 조회하여 일치하는  room id의 개수를 반환 합니다.
- room id는 path variable로 받고 token은 헤더에서 가져와 처리합니다.
- chat_room_members 테이블에 room id와 일치하는 row를 삭제합니다. 
<br>
[LIME-141]: https://uju-lime.atlassian.net/browse/LIME-141?atlOrigin=eyJpIjo …
> [LIME-141] 채팅방 목록 조회, 채팅방 참여, 채팅방 인원수 조회, 채팅방 나가기 기능 구현

- lime-api/src/main/java/com/programmers/lime/global/config/chat/StompWebSocketConfig.java
- lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java
<br>
demo사이트에서 stomp websocket에서 처음 연결할 때 iframe을 요청하는데 이때 X-frame-Options가 deny되어 접속이 불가능합니다.
따라서 demo 사이트에서 일시적인 운영을 위해 spring security frameOptions을 disable 하였습니다. 
추후에 same origin으로 변경할 예정 입니다.  13f18b971d730b6f7ea03cd1aaf7f589abdcf046
[LIME-142]
[LIME-142]: https://uju-lime.atlassian.net/browse/LIME-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIME-142] demo 사이트에서 iframe 사용하기 위해 일시적인 security 변경

- lime-domain/src/main/java/com/programmers/lime/domains/vote/repository/VoteRepositoryForCursorImpl.java
<br>
NO-JIRA
- 정렬 조건을 사용한 투표 목록 조회에서 cursorId로 추가 요청 시 에러가 발생하는 문제가 있었습니다.
1️⃣ [인기순 추가 요청 시 에러 발생 해결](https://github.com/uju-in/lime-backend/commit/6924fe7ca3438ae2b6826cd06e760bc6d4aad6f7)
- voteId로 그룹핑을 했기 때문에 where 대신 having을 사용하여 해결했습니다.
2️⃣ [날짜 정렬 추가 요청 시 에러 발생 해결](https://github.com/uju-in/lime-backend/commit/f93a31cef5391fee0c8138de7b244870ebb450bd)
- 최신순 정렬을 위해 사용하는 create_at이 그룹핑 했을 때 조회되는 컬럼이 아니기 때문에 사용할 수 없습니다. start_at으로 변경하여 해결했습니다.
3️⃣ [마감순 정렬 추가 요청 시 에러 발생 해결](https://github.com/uju-in/lime-backend/commit/0431b633a679bd0b664c438815409b13f0baa64b)
- 마감순으로 정렬을 할 경우 오름차순 정렬이 됩니다. 따라서 커서 아이디도 부등호 방향을 오름차순에 맞춰줘야 합니다. 마감순 정렬만 cursorId 비교 부등호를 변경하여 해결했습니다.
<br>
> [NO-JIRA] 투표 목록 조회 버그 수정

- lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewLikeReader.java
- lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewLikeValidator.java
<br>
[fix: 로그인 하지 않아도 리뷰 좋아요 할 수 있는 버그 수정](https://github.com/uju-in/lime-backend/pull/81/commits/a42b03217f4f77fa1e6202c08150113c17e4eb52)
- 기존 validation 로직이 혼동이 와서 잘 못된 값을 반환 하고 있었습니다.
- 익명 사용자 검사와 중복 좋아요 확인 로직을 확인하기 쉽게 분리하였습니다. 
[LIME-156]
[LIME-156]: https://uju-lime.atlassian.net/browse/LIME-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-156]: https://uju-lime.atlassian.net/browse/LIME-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIME-156] 로그인 하지 않아도 리뷰 좋아요 할 수 있는 버그 수정

- lime-api/src/main/java/com/programmers/lime/domains/vote/api/VoteController.java
- lime-api/src/main/java/com/programmers/lime/domains/vote/application/VoteService.java
- lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java
- lime-api/src/test/java/com/programmers/lime/domains/vote/application/VoteServiceTest.java
- lime-domain/src/main/java/com/programmers/lime/domains/vote/model/VoteStatusCondition.java
- lime-domain/src/testFixtures/java/com/programmers/lime/domains/member/domain/setup/MemberSetUp.java
<br>
LIME-144
1. 올린 투표는 로그인 없어도 조회 가능하도록 변경
2. 내가 참여한 투표는 로그인 상태에서만 확인 가능 (기존의 요구사항과 동일)
- 마이 투표 목록 조회 기능을 기존의 투표 목록 조회와 분리하였습니다.
- 분리한 이유는 마이 투표만 닉네임을 따로 받아야 하기 때문입니다. 기존의 기능에 추가하기에는 너무 복잡해질 것 같아서 분리하는 게 좋다고 생각하였습니다.
<br>
- 기존의 투표 목록 조회에서 내가 올린 투표, 내가 참여한 투표 목록을 조회할 수 없도록 변경하였습니다. 이제 올린 투표와 참여한 투표는 마이 투표 기능에서만 확인 가능합니다.
> [LIME-144] 마이 투표 요구사항 변경

- lime-api/src/main/java/com/programmers/lime/domains/auth/application/OAuthUserService.java
- lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityManager.java
- lime-infrastructure/src/main/java/com/programmers/lime/redis/token/RefreshTokenManager.java
<br>
LIME-165
- 카카오 로그인 시 리프레시 토큰을 저장하지 않던 버그를 수정했습니다.
- 서버가 1대에서 2대로 스케일 아웃 되면서 더 이상 리프레시 토큰 저장소로 로컬 캐시를 사용할 수 없어 레디스로 변경하였습니다.
<br>
> [LIME-165] Refresh Token 저장소 레디스로 변경

- lime-api/src/main/java/com/programmers/lime/domains/feed/api/request/FeedCreateRequest.java
- lime-api/src/main/java/com/programmers/lime/domains/feed/application/FeedService.java
- lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
- lime-domain/src/main/java/com/programmers/lime/domains/feed/domain/Feed.java
- lime-domain/src/main/java/com/programmers/lime/domains/feed/implementation/FeedAppender.java
- lime-domain/src/main/java/com/programmers/lime/domains/feed/model/FeedCreateServiceRequest.java
- lime-domain/src/main/java/com/programmers/lime/domains/feed/model/FeedInfo.java
- lime-domain/src/main/java/com/programmers/lime/domains/feed/repository/FeedRepositoryForCursorImpl.java
- lime-domain/src/testFixtures/java/com/programmers/lime/domains/feed/FeedBuilder.java
- lime-infrastructure/src/main/java/com/programmers/lime/redis/feed/model/FeedRankingInfo.java
<br>
19
피드 생성기능이 수정되었습니다.
1. 기존 버킷 정보를 등록하는 것이 아닌 아이템을 직접 선택해 등록합니다.
2. 등록하는 아이템의 개수는 최대 10개입니다. (검증로직 포함)
3. 검증로직 및 테스트 코드는 동작하는 최소한의 수준으로만 수정했습니다.
**4. 사용시 name이라는 컬럼(bucketInfo에 있던것임) 을 삭제 후 사용해주시길 바랍니다.**
<br>
> [LIME-19] 피드 생성 기능 수정
