uju-in/lime-backend

lime-api/src/main/java/com/programmers/lime/domains/member/application/MemberService.java
lime-infrastructure/src/main/java/com/programmers/lime/s3/config/S3Configuration.java

<br>
LIME-6
네이버 클라우드 버킷을 사용하기 위해 end point를 변경해야 합니다!
따라서 이를 추가하기 위해 yml에서 endpoint를 가져오도록 추가 하였습니다!
기존 코드를 최대한 건드리지 않고 기능 추가하였습니다!
저장소가 aws에서 네이버 클라우드에 저장되는 것 외에 다른 점은 없습니다!

[LIME-6] 네이버 클라우드 변경으로 인한 기존 설정 파일 변경 

---

.github/workflows/CICD.yml

<br>
LIME-7
main에 merge 하기 위한 pr이 merge되서 close 될 때 github action이 실행되도록 yml 파일 수정

[LIME-7] github action의 yml 파일 수정 

---

lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
lime-domain/src/main/java/com/programmers/lime/domains/member/domain/vo/Nickname.java

<br>
NO-JIRA
👉 추가 요구사항(닉네임에 한글 가능)에 맞게 닉네임 패턴에 한글을 추가하였습니다.
<br>

[NO-JIRA] 닉네임 패턴에 한글 추가

---

lime-api/src/main/java/com/programmers/lime/domains/auth/dto/OAuthAttributes.java
lime-api/src/main/java/com/programmers/lime/global/config/security/OAuth2UserService.java
lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java

<br>
1
Bean의 컴포넌트 스캔 범위 밖에 Oauth2UserService 파일을 두었음
<br>

[LIME-1] Oauth2UserService 위치 변경

---

lime-api/src/main/java/com/programmers/lime/domains/member/api/dto/request/MemberCheckNicknameRequest.java
lime-api/src/main/java/com/programmers/lime/domains/member/api/dto/request/MemberUpdateProfileRequest.java
lime-domain/src/main/java/com/programmers/lime/domains/member/domain/vo/Nickname.java

<br>
NO-JIRA
```
- 닉네임 중복 확인 시 한글도 입력 가능하도록 변경
- 프로필 업데이트 요청값에 유효성 검증 추가
```
<br>

[NO-JIRA] 프로필 업데이트, 닉네임 중복확인 request dto 유효성 검증 추가

---

lime-api/src/main/java/com/programmers/lime/global/config/security/auth/handler/OAuth2LoginSuccessHandler.java

<br>
LIME - 1 
닉네임이 한글일 경우 적절한 주소로 리다이렉트되지 못하고 400에러를 못하는 문제가 있음.
전체 주소를 utf-8로 인코딩 해 리다이렉트를 시켜 문제를 해결함
<br>

[LIME - 1] 프로필 등록후 로그인 시 인코딩 된 주소로 redirect

---

lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java

<br>
NO-JIRA
- CI/CD 실패 원인을 찾아보니 패키지 변경된 클래스의 이전 import 문이 문제였음
<br>
- [x]  아니요

[!HOTFIX] 오류나는 import문 제거

---

lime-api/src/main/java/com/programmers/lime/domains/item/api/ItemController.java
lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/ItemEnrollRequest.java
lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemService.java
lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/ItemCursorReader.java
lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemRepositoryForCursor.java
lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemRepositoryForCursorImpl.java

<br>
- 아이템 목록조회에 취미를 추가하였습니다! 0a0541cbe86cf18b8555f0299ae48897f03be13b
- 목록조회 관련 스웨거 문서 수정 및 취미 변수명 수정을 하였습니다. 5693a96b6d5f8d239cace697bb3532244a2e011e 83cf6f95f83ec6dfb6e8b2044fdc932234008c00
[LIME-52]
아이템 목록조회할 경우 취미 조건을 추가하였습니다! 0a0541cbe86cf18b8555f0299ae48897f03be13b
<br>
[LIME-52]: https://uju-lime.atlassian.net/browse/LIME-52?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LIME-52] 아이템 목록 조회에 취미 추가 

---

lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemRepositoryForCursorImpl.java
lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemRepositoryForCursorImpl.java
lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewCursorReader.java
lime-domain/src/main/java/com/programmers/lime/domains/review/model/ReviewCursorSummary.java
lime-domain/src/main/java/com/programmers/lime/domains/review/model/ReviewInfo.java
lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewRepositoryForCursor.java
lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewRepositoryForCursorImpl.java
lime-domain/src/test/java/com/programmers/lime/domains/review/implementation/ReviewCursorReaderTest.java
lime-domain/src/testFixtures/java/com/programmers/lime/domains/review/ReviewCursorSummaryBuilder.java
lime-domain/src/testFixtures/java/com/programmers/lime/domains/review/ReviewInfoBuilder.java

<br>
- 로그인한 사용자가 각 리뷰를 좋아요를 눌렀는지 확인하는 값을 반환 합니다.
- 로그인한 사용자가 작성한 리뷰인지 확인하는 데이터는 reviewLoginMemberStatus 하위로 변경하였습니다.
최종적으로 리뷰 목록 조회를 할 경우 아래와 같이 json이 반환 합니다.
```json
{
"nextCursorId": "0000000000000696",
"itemReviewTotalCount": 686,
"totalCount": 20,
"reviews": [
{
"cursorId": "0000000400000692",
"memberInfo": {
"memberId": 2,
"nickname": "고란",
"profileImage": "http://k.kakaocdn.net/dn/1G9kp/btsAot8liOn/8CWudi3uy07rvFNUkk3ER0/img_110x110.jpg",
"level": 10
},
"reviewSummary": {
"reviewId": 692,
"rate": 3,
"content": "ㅎㅇㅎㅇ",
"imageUrls": [
"https://lime-bucket.kr.object.ncloudstorage.com/review-images/35a2ca11-926a-488f-8b00-c1a00b6a4db1png",
"https://lime-bucket.kr.object.ncloudstorage.com/review-images/af629b4e-ef17-46f9-971b-2f6e7108bad2png", …
```

[LIME-79] 리뷰 목록 조회에 로그인한 사용자 관련 기능 추가 

---

lime-domain/src/main/java/com/programmers/lime/domains/review/model/ReviewLoginMemberStatus.java

[NO-JIRA] 로그인한 사용자 정보를 담는 모델 클래스 추가

---

lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewLikeService.java

<br>
[LIME-86]
[LIME-86]: https://uju-lime.atlassian.net/browse/LIME-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LIME-86] 리뷰 좋아요를 저장할 때 멤버 아이디가 저장 되도록 버그 수정

---

lime-api/build.gradle
lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java

[NO-JIRA] 그라파나 설정 추가

---

lime-api/src/main/java/com/programmers/lime/domains/review/api/ReviewController.java
lime-api/src/main/java/com/programmers/lime/domains/review/api/dto/request/ReviewUpdateRequest.java
lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewService.java
lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewValidator.java
lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewImageReader.java
lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewImageRemover.java
lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewImageRepository.java
lime-infrastructure/src/main/java/com/programmers/lime/s3/S3Manager.java

<br>
[LIME-85]
- 기존 이미지를 수정, 추가를 나눠서 생각하였습니다.
- 기존 이미지를 삭제 할 때 삭제할 이미지의 URL를 입력으로 받습니다.
- 기존 리뷰에 이미지를 추가할 경우 리뷰 이미지 생성과 똑같이 multipart로 입력받아 버킷에 저장합니다. 
<br>
[LIME-85]: https://uju-lime.atlassian.net/browse/LIME-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LIME-85] 리뷰 이미지 수정 기능 추가 

---

lime-infrastructure/build.gradle
lime-infrastructure/src/main/resources/logback-spring.xml

<br>
[LIME-94]
- AWS 클라우드 워치 삭제 후 필요 없는 의존성이라는  경고가 생겨 삭제하였으나 실제 빌드 후 예외가 발생하여 다시 추가하였습니다. 
[LIME-94]: https://uju-lime.atlassian.net/browse/LIME-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LIME-94] Loki 서버 전송을 위한 로그백 설정 

---

lime-domain/src/main/java/com/programmers/lime/domains/vote/model/VoteDetailInfo.java

<br>
NO-JIRA
- 투표 상세 조회에 취미를 표시하는 요구사항이 추가되었습니다.
- VoteDetatilInfo에 취미 컬럼을 추가하였습니다.
<br>

[NO-JIRA] 투표 상세 조회 결과에 취미 추가

---

lime-api/src/main/java/com/programmers/lime/domains/favorite/api/FavoriteItemController.java
lime-api/src/main/java/com/programmers/lime/domains/favorite/application/FavoriteItemService.java
lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
lime-domain/src/main/java/com/programmers/lime/common/model/FavoriteType.java
lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/IFavoriteReader.java
lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFavoriteInfoReader.java
lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFavoriteReader.java
lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderFavoriteInfoReader.java

<br>
- /api/favorites 조회할 때 favoriteType에 따라 favorite을 반환 
[LIME-107]
[LIME-107]: https://uju-lime.atlassian.net/browse/LIME-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LIME-107] 찜 목록 조회 기능 추가

---

lime-api/build.gradle
lime-infrastructure/build.gradle

[NO-JIRA] 의존성 위치 변경 

---

lime-infrastructure/src/main/java/com/programmers/lime/redis/config/RedisConfig.java

<br>
NO-JIRA
- 레디스 서버의 무차별 공격을 받아 서버 보안을 추가하는 김에 레디스 비밀번호 설정도 함께 추가하였습니다.
- https://passwd.tistory.com/entry/Redis-%EB%B9%84%EB%B0%80%EB%B2%88%ED%98%B8-%EC%84%A4%EC%A0%95
- https://velog.io/@jaewonlee/SpringBoot%EB%A1%9C-Redis-%EC%84%9C%EB%B2%84-%EC%84%A4%EC%A0%95-%EB%B0%A9%EB%B2%95
- https://webisfree.com/2018-04-19/%EB%A6%AC%EB%88%85%EC%8A%A4(linux)-%EC%82%AC%EC%9A%A9%EC%9E%90-%ED%8C%A8%EC%8A%A4%EC%9B%8C%EB%93%9C-%EB%B3%80%EA%B2%BD-%EB%B0%A9%EB%B2%95
- https://mebadong.tistory.com/34
<br>

[NO-JIRA] 레디스 보안 설정 추가

---

README.md

docs : README 초안 업데이트

---

lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java

[LIME-122] 카카오 토큰요청 callback 경로 버그 수정

---

lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java

[LIME-122] requestMatchers 콜백 경로 추가

---

.github/workflows/CICD.yml
Dockerfile

<br>
[LIME-145]
[LIME-145]: https://uju-lime.atlassian.net/browse/LIME-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LIME-145] ci/cd 수정 

---

.github/workflows/CICD.yml

<br>
적용 과정을 아래 노션 링크에 정리 하였습니다 ~! 참고 부탁 드립니다. 😊
- [전체 소개 페이지](https://night-pump-292.notion.site/Blue-Green-2daa88cee1f64762b2e5be5d37ce794a?pvs=4)
- [Blue/Green 전략으로 배포하기 - part1](https://www.notion.so/Blue-Green-part-1-9e2d054b57b94ce3a7998ee6f73e2f39?pvs=4)
- [Blue/Green 전략으로 배포하기 - part2](https://www.notion.so/Blue-Green-part-2-44848fcf1dc640b7950911dad0046351?pvs=4)
- [Blue/Green 전략으로 배포하기 - part3](https://www.notion.so/Blue-Green-part-3-f3a53bcd61a1454ab54cfe6ad9dc8072?pvs=4)
- [Blue/Green 전략으로 배포하기 - part4](https://night-pump-292.notion.site/Blue-Green-part-4-2da73beb9eb0437c8faae6628b2bf653?pvs=4)
[LIME-145]
[LIME-145]: https://uju-lime.atlassian.net/browse/LIME-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …

[LIME-145] Blue/Green 배포 전략 변경

---

lime-api/src/main/java/com/programmers/lime/domains/favorite/application/FolderService.java
lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderRemover.java

<br>
[fix: 폴더 이름 수정할 경우 default 폴더로 이름 변경되는 버그 수정](https://github.com/uju-in/lime-backend/commit/7b08d47d56ac00a63b44aeaa6e4938c5fb8e90da)
- 이름 변경 전에 validation 하도록 수정하였습니다.
[fix: 폴더 삭제할 경우 하위 아이템 삭제 안되는 버그 수정](https://github.com/uju-in/lime-backend/commit/53081ddab27fde773284420c040729a51dc2bd67)
- 잘 못된 인자로 메서드 호출하고 있어서 그 부분을 수정하였습니다.
[LIME-157]
[LIME-157]: https://uju-lime.atlassian.net/browse/LIME-157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LIME-157] 찜 관련 버그 수정 

---

lime-api/src/main/java/com/programmers/lime/domains/member/api/dto/response/MemberCheckJwtResponse.java
lime-api/src/main/java/com/programmers/lime/domains/member/application/MemberSecurityManager.java
lime-api/src/main/java/com/programmers/lime/domains/member/application/dto/response/MemberCheckJwtServiceResponse.java

<br>
no-jira
역할을 확인할 수 있도록 기능을 추가했습니다.
<br>

[NO-JIRA] jwt에서 역할 확인할 수 있도록 수정

---

lime-api/src/main/java/com/programmers/lime/domains/chat/application/ChatService.java
lime-api/src/main/java/com/programmers/lime/domains/chatroom/application/ChatRoomService.java
lime-api/src/main/java/com/programmers/lime/global/config/chat/message/ChatRoomRemoveSessionListener.java
lime-api/src/main/java/com/programmers/lime/global/config/chat/message/SimpleChatListener.java
lime-api/src/main/java/com/programmers/lime/global/event/chat/ChatSendMessageEventListener.java
lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/ChatRedisMessageBrokerConfig.java
lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/listener/ChatRoomRemoveAllSessionListenerImpl.java
lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/listener/IChatRoomRemoveSessionListener.java
lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/model/ChatRoomRemoveAllSessionInfo.java
lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/publisher/ChatRoomRemoveSessionPublisher.java
lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/publisher/IChatRoomRemoveSessionPublisher.java

<br>
채팅 관련 버그 수정 하였습니다.
- [fix: 채팅 추가할 경우 채팅이 보이지 않는 버그 수정](https://github.com/uju-in/lime-backend/commit/6457c322f51c00486c4b446bd8fbb5b5805ac267)
- [fix: 캐시에서 ChatType 가져오지 않는 버그 수정](https://github.com/uju-in/lime-backend/commit/90216c5aed9a3abf8aac08e87cab52f1db076114)
- [fix: 입장과 퇴장 메시지가 전송되지 않는 버그 수정](https://github.com/uju-in/lime-backend/commit/a8436d03418502e6b1d7aa76ac9c3eb0dfe01a63)
- [fix: null exception 예외 수정](https://github.com/uju-in/lime-backend/commit/3300a01aaf53a692959ef8d4c257207e5b77f464)
- [feat: 방을 나가면 전체 WAS 서버에서 기존 연결을 끊을 수 있도록 기능추가](https://github.com/uju-in/lime-backend/commit/4fc555b3593fff3b185e9b95af892beaf29d1557)
[NO-JIRA]

[NO-JIRA] 채팅 버그 수정

---

lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemRepositoryForCursorImpl.java

<br>
[fix: 아이템 정렬 버그 수정](https://github.com/uju-in/lime-backend/commit/a4f0ba466b9d5f5c23d94588cdecf22998d0ce2b)
[LIME-165]
- having과 where 절을 나눠 아이템 정렬되도록 수정하였습니다.

[LIME-165] 아이템 정렬 버그 수정

---

lime-api/src/main/java/com/programmers/lime/domains/chat/api/ChatController.java
lime-api/src/main/java/com/programmers/lime/domains/chatroom/api/ChatRoomController.java
lime-api/src/main/java/com/programmers/lime/domains/favorite/api/FavoriteItemController.java
lime-api/src/main/java/com/programmers/lime/domains/item/api/ItemController.java
lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/ItemSearchRequest.java
lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemEnrollService.java
lime-api/src/main/java/com/programmers/lime/domains/review/api/ReviewController.java
lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java
lime-api/src/main/java/com/programmers/lime/global/cursor/CursorRequest.java
lime-api/src/main/java/com/programmers/lime/global/error/GlobalExceptionHandler.java
lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java

<br>
item, review, favorite, chat rooms
1. API의 권한 설정을 세부적으로 조정 하였습니다. c66c5414f928d639ec70b03b7453f9dca8b8abd9 0ddec5851bdca14f24e6925a64c1b2a424405339 0aae84f04778979b6b417f8ef1c480fd7063f497
2. Swagger 문서 내용 수정 및 Model Attribute가 request param으로 보일 수 있도록 스웨거 문서 수정 하였습니다. 045732fd44a16a3549d9ed6aaf5674b84b7134b3
3. 필수적으로 필요한 이미지가 들어오지 않았을 경우 해당하는 예외를 내려 주도록 하였습니다. c2272aa100aa2bb150093846ef3d0cc13e5fba65
4. 더 이상 사용하지 않는 반환 값을 제거 했습니다. 2bbd55645a00b405d4afbf3ba85338c638bd0200 e034562ab852f35548b30eebdc4c84a25344bd4d
[NO-JIRA]

[NO-JIRA] sercurity swagger returntype 리팩토링

---

lime-api/src/main/java/com/programmers/lime/domains/chat/application/ChatService.java
lime-api/src/main/java/com/programmers/lime/global/cache/CacheType.java
lime-api/src/main/java/com/programmers/lime/global/event/chat/ChatAppendEventListener.java
lime-api/src/main/java/com/programmers/lime/global/event/chat/ChatSendMessageEventListener.java
lime-api/src/main/java/com/programmers/lime/global/scheduler/ChatCacheAppendScheduler.java
lime-domain/src/main/java/com/programmers/lime/domains/chat/implementation/ChatAppender.java
lime-domain/src/main/java/com/programmers/lime/domains/chat/repository/ChatJdbcTemplateRepository.java
lime-domain/src/main/java/com/programmers/lime/domains/member/implementation/MemberModifier.java
lime-domain/src/main/java/com/programmers/lime/domains/member/implementation/MemberReader.java
lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/ChatBufferManager.java
lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/ChatCursorCacheReader.java
lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/ChatSessionRedisManager.java
lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/lua/ChatDQueueScriptManager.java
lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/lua/ChatLLScriptManager.java
lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/lua/DQueueReadScript.java
lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/lua/LLReadScript.java
lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/model/ChatCursorCache.java
lime-infrastructure/src/main/java/com/programmers/lime/redis/config/RedisConfig.java
lime-infrastructure/src/main/resources/ReadByDQueue.lua

<br>
[LIME-167]
채팅 추가 기능 개선 PR 입니다.
다음 링크에 상세 내용 정리하였습니다. 참고 바랍니다.
https://www.notion.so/8e7bf4c3488a4a2aa8c858ac02d14965?pvs=4
[LIME-167]: https://uju-lime.atlassian.net/browse/LIME-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LIME-167] 채팅 전송 기능 개선 
